
= Spring Fundamentals, Aspect Oriented Programming
:sectnums:

One of the most fascinating capabilities of the Spring framework is the ability to easily implement Aspect Oriented Programming (AOP). In this lab, we will learn how to use AOP in Spring.

Within the codebase you will find ordered *TODO* comments that describe what actions to take for each step.  By finding all files containing *TODO*, and working on the steps in numeric order, it is possible to complete this exercise without looking at the instructions.  If you do need guidance, you can always look at these instructions for full information.  Just be sure to perform the *TODO* steps in order.

Solution code is provided for you in a separate folder, so you can compare your work if needed.  For maximum benefit, try to complete the lab without looking at the solution.

== Open the project.

==== Use your IDE to open `C:\LabFiles\50-spring-aop` (adjust this location as needed).

==== TODO 01: Open `build.gradle`.  Notice there are three new dependencies added to support AOP:

* org.aspectj:aspectjweaver
* org.springframework:spring-aop
* org.springframework:spring-aspects

Spring uses _AspectJ_ internally for some of its features, such as pointcut syntax.

== Enable Aspect Oriented Programming

==== TODO-02: Open `src/test/java/com.example.Config.java` Add an annotation to this configuration class to enable AspectJ proxying:
[source,java]
----
@EnableAspectJAutoProxy
@Configuration   
@PropertySource("classpath:app.properties")
@ComponentScan("com.example")
public class Config {
----
The `@EnableAspectJAutoProxy` annotation serves as a master switch to enable AOP capability within a Spring application.  It tells Spring to look for beans annotated with `@Aspect`, process `@Pointcut` annotations, and create proxies for all beans requiring them.


== Build the `LoggingAspect`

==== TODO-03: Open `src/main/java/com.example.as[ect.LoggingAspect.java`.  Annotate this class as an aspect and a component.
. Add the `@Aspect` annotation to the class.
. Add the `@Component` annotation to the class.
[source,java]
----
@Aspect
@Component
public class LoggingAspect {
----
The `@Aspect` annotation tells Spring that this class contains advice and pointcut definitions.  The `@Component` annotation registers this class as a Spring bean.

==== TODO-04: Find the `logActivity()` method.  Annotate this method to execute before other methods are called. The pointcut should select any method starting with "get*" in any class in the `com.example.dao` package.  
.  Place the `@Before` annotation on the method.  It indicates that the advice should be executed before the target method is called.
.  The pointcut expression should be `execution(* com.example.dao.**.get*(..))`.  
* *execution* indicates we wish to select a method execution.
* The first wildcard *** matches any return type.
* *com.example.dao.** matches any class in the `com.example.dao` package.
* *get** matches any method starting with "get".
* *(..)* matches any number of parameters; zero or more.
. The "Examples" section in [Spring Framework Reference](https://docs.spring.io/spring-framework/reference/core/aop/ataspectj/pointcuts.html) has similar examples you may find useful.
[source,java]
----
    @Before("execution(* com.example.dao.*.get*(..))")
    public void logActivity(JoinPoint joinPoint) {
----

==== TODO-05: Alter the line of code defining "methodName".  Use the joinPoint parameter to get the class name and method name being called.  The name will be used to log the name of the method to the console. 
* The `joinPoint` parameter provides information about the target method on the target object.  It contains information about the method's signature.
[source,java]
----
        String methodName = 
            joinPoint.getSignature().getDeclaringTypeName() + 
            "." + 
            joinPoint.getSignature().getName();
        System.out.println("The " + methodName + " method was called.");
----
==== TODO-06: Organize your imports, save your work.  Move on to the next step.


== Test the `LoggingAspect`
To effectively test the LoggingAspect, we will need to execute methods on beans which should be affected by the advice.

==== TODO-07: Open `src/test/java/com.example.dao.PurchaseDaoImplTests.java`.  Annotate this class to make it a Spring test class.  Include the configuration class you wish to load.
* The `@SpringJUnitConfig` annotation tells Spring to load the `Config` configuration class specified in the annotation.
[source,java]
----
@SpringJUnitConfig(Config.class)
public class PurchaseDaoImplTests {
----

==== TODO-08: Inject a `PurchaseService` object.
[source,java]
----
@Autowired PurchaseService service;
----

==== TODO-09: Organize imports, save your work.
* Notice that there are two existing test methods in this class.  Observe what they do, each calls methods on the `PurchaseService` object which begin with "get".  This should trigger the advice in the `LoggingAspect` class.
* Run the tests.  You should see the output from the `LoggingAspect` class in the console.  If you do not see the expected output, review your annotations and pointcut expressions.


== OPTIONAL: Build the `StopWatchAspect`
If you have time (and if you can't get enough of AOP), you can build another aspect to measure the time it takes to execute methods.

Consider that such a timer would need to 1) capture the current time before a method is called 2) capture the current time after the method is called 3) calculate the difference between the two times.  We will need an advice type that can execute both before and after a method invocation.

==== TODO-10: Open `src/main/java/com.example.aspect.StopwatchAspect.java`.  Annotate this class as an aspect and a component.
. Add the `@Aspect` annotation to the class.
. Add the `@Component` annotation to the class.
[source,java]
----
@Aspect
@Component
public class StopwatchAspect {
----

==== TODO-11: Find the `recordTime()` method.  Annotate this method with an advice type capable of capturing activity both before and after a method is called. The pointcut should select any method starting with "save*" in the `com.example.dao` package.
. Place the `@Around` annotation on the method.  It indicates that the advice should be executed before and after the target method is called.
. The pointcut expression should be `execution(* com.example.dao.*.save*(..))`.
* *execution* indicates we wish to select a method execution.
* The first wildcard *** matches any return type.
* *com.example.dao.** matches any class in the `com.example.dao` package.
* *save** matches any method starting with "save".
* *(..)* matches any number of parameters; zero or more.
. The "Examples" section in [Spring Framework Reference](https://docs.spring.io/spring-framework/reference/core/aop/ataspectj/pointcuts.html) has similar examples you may find useful.
[source,java]
----
    @Around("execution(* com.example.dao.*.save*(..))")
    public Object recordTime(ProceedingJoinPoint joinPoint) throws Throwable {
----

==== TODO-12: Within the advice method, instantiate a new `Stopwatch` object and call its `start()` method.
* The `Stopwatch` class is an inner class provided for you.
[source,java]
----
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.start();
----

==== TODO-13: Within the try / catch block, call the target method on the target object, assign the result to the `result` variable.
* With `@Around` advice, the target method will not be called unless coded explicitly.
* Use the `joinPoint.proceed()` method to call the target method on the target object.
* Critical: make sure to capture the result of the target method in a variable. This value must be returned to the caller.
[source,java]
----
        Object result = joinPoint.proceed();
----

==== TODO-14: Within the finally block, stop the stopwatch and display the elapsed time.
* Call the `stop()` method on the `stopwatch` object.
* Call the `displayElapsedTime()` method on the `stopwatch` object, passing the `methodName`.  Notice how the `methodName` is derived.
[source,java]
----
        stopwatch.stop();
        stopwatch.displayElapsedTime(methodName);
----

==== TODO-15: Organize imports, save your work.  Move on to the next step.

== Test the `StopwatchAspect`


==== TODO-16: Return to `src/test/java/com.example.dao.PurchaseDaoImplTests.java`.  Find the `savePurchase()` method.  Remove the `@Disabled` annotation.  Run the test, it should pass AND you should see the elapsed time in the console.
* The `@Disabled` annotation is used to temporarily disable a test.
* If you do not see the expected output, review your annotations and pointcut expressions.

== Review

In this lab we learned:

* How to enable Aspect Oriented Programming in Spring.
* How to create an aspect.
* How to create pointcut expressions.
* How to create advice methods.
* How to test aspects.


